### PR TITLE
Replace deprecated Config with RbConfig

### PR DESCRIPTION
**Pull request by runlevel5**
Replace deprecated `Config` with `RbConfig`

### CODE REVIEW

**Comment by seanmarcia** [comment]
Awesome commit thanks for this! It was pulled in as part of Foomip's commit! Thanks so much! Sorry it took so long for anyone to reply, the project was unmaintained for a while and I've just been given access.

**Comment by runlevel5** [comment]
@SeanMarcia thanks for pulling, if you need a hand, please let me know, I could spare few hours working on this project as I have been into this for a while

**Comment by seanmarcia** [comment]
Any help would be greatly appreciated! It is a little overwhelming right now to be honest. I've been slowly reviewing and bringing in the pull requests as well as looking over the various forks that people have made (there are a lot of them.) We've upgraded it to Rails 3.2.15/Ruby 1.9.3 to make it more current and will work on moving it to 4.0.0 and ruby 2.0.0. I think one of the next things we need to do is remove rcov and decide what/if we want to replace it with. I'm thinking that it will probably be simplecov; if we do pick simplecov, should we just make a simplecov tab in the dashboard?

Sorry for the long rambling response :) Those are the things going through my head currently but I'm open to any help as I realize there are a lot of things I'm probably missing :)

**Comment by runlevel5** [comment]
I'd love to give much help as I could. Can you please file these features as GH issues? I'll get onto it once I am available. Cheers

**Pull request closed without merging**
