### PR TITLE
Sometimes we need to pass variables to the build command through environment, but because of Bundler.with_clean_env it is not possible now

### PR DESCRIPTION
**Pull request by kpumuk**
Added ability to set custom environment variables in cruise_config.rb via project.environment hash

### CODE REVIEW

**Comment by bguthrie** [comment]
This seems like a useful feature to me, and eventually a good way to handle environment variable settings across multiple platforms. Anyone else have any strong feelings?

**Comment by kovyrin** [comment]
We at Scribd.com use this functionality to start multiple build commands in parallel (each receives its ID via environment) + do some ruby specs tuning using ENV variables (some tests run only on CI and are enabled using those vars). It would be really useful to have this feature in vanilla CC.rb.

**Comment by bguthrie** [comment]
Were you doing this before Bundler integration was added? How? And do you feel okay about continuing to use Bundler.with_clean_env, or are we better off removing that and allowing you to go back to the way you used to manage it?

**Comment by kpumuk** [comment]
We were doing this using `ENV['xxx'] = 'yyy'` in `cruise_config.rb`. I don't why we should stop using `Bundler.with_clean_env` - it looks like a right way to do the thing.

**Comment by ketan** [comment]
This seems like a valid requirement. But mucking around with the parent processes' ENV hash seems to be a less than ideal. IO.popen already accepts a hash to do this better: http://www.ruby-doc.org/core/classes/IO.html#M000880

Also checkout http://www.ruby-doc.org/core/classes/Kernel.html#M001442 for options that are accepted at the end of IO.popen.

I'd like to propose changing Build#run to something like this (keeping the rest of this changeset as is) Thoughts?

``` ruby
class Build
  def run
    ...
      in_clean_environment_on_local_copy do
        if @project.uses_bundler?
          execute self.bundle_install, :stdout => build_log, :stderr => build_log, :env => self.project.environment
        end
        execute self.command, :stdout => build_log, :stderr => build_log, :env => self.project.environment
      end
    ...
  end
end
```

**Comment by ketan** [comment]
Here's what I tweaked based on changeset from @kpumuk https://github.com/ketan/cruisecontrol.rb/commit/7f3ebbde349ccaa08da57998a85b9cc15933f4f6

**Comment by ketan** [comment]
Merging in my patchset at https://github.com/ketan/cruisecontrol.rb/commit/7f3ebbde349ccaa08da57998a85b9cc15933f4f6. Shout out if there's something that I've missed out.

**Pull request closed without merging**
