### PR TITLE
Rake 0.9.0 compatibility, schema loading, routing fix

### PR DESCRIPTION
**Pull request by tobsch**
Hi guys,

this will 
- make the Rake tasks work again (Rake 0.9).
- make the project overview work again (routing fix)
- introduce schema loading in favor to migrations

The changes are very basic.
Would be neat to see them in the master.

Best,

Tobias

### CODE REVIEW

**Comment by bguthrie** [comment]
I've merged a separate pull request that locks the Gemfile and Rails version to ones that no longer break on upgrade. I confess I haven't been following the Rake upgrade closely--is loading the DSL by hand the accepted way of handling this going forward, or are we better off sticking to an older version until things have stabilized? Happy to merge if I receive some assurance that including Rake::DSL isn't just a temporary fix.

Thanks very much for the fixes to rss routes and schema loading. Looking forward to merging them.

**Comment by tobsch** [comment]
Yep, it seems temporarly.
I'll stick to "bundle exec rake" then :-)

Schema Loading & The routing thing should be okay though.

**Comment by gnufied** [comment]
This has been fixed in Rails itself and should not be required here once cruisecontrol.rb is upgraded to Rails 3.1

**Comment by bguthrie** [comment]
I've cherry-picked 2baa78c and bf56fc2 from adyard/master and they've entered tw/master as 1d66669a1b99748f528c3ffda8b9e82fdac79826 and a69db608a0b65c81948599a26a5a80244651e547, respectively. Many thanks for the contribution!

**Pull request closed without merging**
